### ISSUE TITLE
Compatible with Phaser v3?

### ISSUE THREAD

**Issue by jorbascrumps** [amaccann/phaser-navmesh-generation#23]
Is this plugin compatible with Phaser v3? I'm having some issues getting up and running.

**Comment by amaccann** [comment]
@jorbascrumps This specific repo is Phaser 2: however, I migrated it to Phaser 3 a few months ago; see here: https://www.npmjs.com/package/@pixelburp/phaser3-navmesh-generation

Hopefully, it should work in your Phaser 3 project without issue. Let me know?

**Comment by jorbascrumps** [comment]
@amaccann That is great news! 🙏 I have an idea I'd like to prototype and what you've created would help immensely.

Is there a public repo for the new version? Seems the link on npm 404s. If so, we can close this issue and if I run into any problems I can report there.

**Comment by amaccann** [comment]
@jorbascrumps I made the P3 github repo private for the time being, but you should still be able to use the final build / package anyway. If you have any issues, post them in this repo for now, & I'll take a look; will look at making the repo public at a later point. It needs a little TLC as it has become quite stale.

**Comment by jorbascrumps** [comment]
@amaccann I understand, half my repos are well past expired 😁 Thanks again for your help!
